USE EDDSQoS
GO

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'QoS_HourlyWaitStats' and TABLE_SCHEMA = 'EDDSDBO')
BEGIN
	DROP TABLE eddsdbo.QoS_HourlyWaitStats
END

GO

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'QoS_HourlyWaitStatsMaster' and TABLE_SCHEMA = 'EDDSDBO')
BEGIN
	DROP TABLE eddsdbo.QoS_HourlyWaitStatsMaster
END

GO

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'QoS_Waits' and TABLE_SCHEMA = 'EDDSDBO')
BEGIN
	DROP TABLE eddsdbo.QoS_Waits
END

GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[eddsdbo].[QoS_GetWaits]') AND type in (N'P', N'PC'))
BEGIN
	DROP PROCEDURE eddsdbo.QoS_GetWaits
END