USE EDDSQoS
GO

IF EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'QoS_VarscatOutput' AND COLUMN_NAME = 'GlassRunID')
BEGIN
	EXEC sp_rename 'eddsdbo.QoS_VarscatOutput.GlassRunID', 'AgentID', 'COLUMN'
END