USE EDDSQoS
GO

IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'QoS_VarscatOutputDetail' AND TABLE_SCHEMA = 'EDDSDBO') 
	ALTER TABLE eddsdbo.QoS_VarscatOutput ALTER COLUMN CreatedBy nvarchar(200);