USE EDDSQoS
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'QoS_VarscatOutput'
	AND TABLE_SCHEMA = 'eddsdbo'
	AND COLUMN_NAME = 'DatabaseName'
	AND CHARACTER_MAXIMUM_LENGTH < 128)
BEGIN
	ALTER TABLE eddsdbo.QoS_VarscatOutput
	ALTER COLUMN DatabaseName nvarchar(128)
END