USE EDDSQoS
GO

IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'QoS_VarscatOutputDetail' AND COLUMN_NAME = 'QueryID')
BEGIN
	ALTER TABLE eddsdbo.QoS_VarscatOutputDetail
	ADD QueryID UNIQUEIDENTIFIER NULL
END