USE EDDSQoS
GO

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'QoS_Waits' and TABLE_SCHEMA = 'EDDSDBO')
BEGIN
	IF NOT EXISTS (SELECT TOP 1 WaitTypeID FROM eddsdbo.QoS_Waits WHERE WaitType = 'RESOURCE_SEMAPHORE_QUERY_COMPILE')
	BEGIN
		INSERT INTO eddsdbo.QoS_Waits (WaitType)
		VALUES ('RESOURCE_SEMAPHORE_QUERY_COMPILE')
	END
	
	IF NOT EXISTS (SELECT TOP 1 WaitTypeID FROM eddsdbo.QoS_Waits WHERE WaitType = 'CMEMTHREAD')
	BEGIN
		INSERT INTO eddsdbo.QoS_Waits (WaitType)
		VALUES ('CMEMTHREAD')
	END
	
	IF NOT EXISTS (SELECT TOP 1 WaitTypeID FROM eddsdbo.QoS_Waits WHERE WaitType = 'THREADPOOL')
	BEGIN
		INSERT INTO eddsdbo.QoS_Waits (WaitType)
		VALUES ('THREADPOOL')
	END
END