USE EDDSPerformance

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'QoS_tempServers' AND TABLE_SCHEMA = 'EDDSDBO')
BEGIN
	SELECT ServerName
	FROM eddsdbo.QoS_tempServers WITH(NOLOCK)
	WHERE Failed = 1
	ORDER BY ServerName;
END