IF NOT EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'MockHours' AND TABLE_SCHEMA = N'EDDSDBO') 
BEGIN

	CREATE TABLE [eddsdbo].[MockHours](
		[HourTimeStamp] [datetime] NOT NULL,
	 CONSTRAINT [PK_MockHours] PRIMARY KEY CLUSTERED 
	(
		[HourTimeStamp] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

END