IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'MockServer' AND TABLE_SCHEMA = N'EDDSDBO') 
BEGIN
DROP TABLE eddsdbo.[MockServer]
END

CREATE TABLE [eddsdbo].[MockServer](
		[Id] int IDENTITY(1,1) NOT NULL,
		[ServerID] [int] NOT NULL
 CONSTRAINT [PK_MockServer] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_ServerId] UNIQUE NONCLUSTERED 
(
	[ServerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]