IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'MockHours' AND TABLE_SCHEMA = N'EDDSDBO') 
BEGIN
	DROP TABLE eddsdbo.[MockHours]
END

CREATE TABLE [eddsdbo].[MockHours](
		[Id] int IDENTITY(1,1) NOT NULL,
		[HourId] [int] NOT NULL
 CONSTRAINT [PK_MockHours] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_HourId] UNIQUE NONCLUSTERED 
(
	[HourId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]