USE EDDSPerformance
GO

IF EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ServerDiskDW' AND COLUMN_NAME = 'DiskAvgSecPerRead')
BEGIN
	EXEC sp_rename 'eddsdbo.ServerDiskDW.DiskAvgSecPerRead', 'DiskAvgReadsPerSec', 'COLUMN'
END

GO

IF EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ServerDiskDW' AND COLUMN_NAME = 'DiskAvgSecPerWrite')
BEGIN
	EXEC sp_rename 'eddsdbo.ServerDiskDW.DiskAvgSecPerWrite', 'DiskAvgWritesPerSec', 'COLUMN'
END

GO

IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ServerDiskDW' AND COLUMN_NAME = 'DiskSecPerRead')
BEGIN
	ALTER TABLE eddsdbo.ServerDiskDW
	ADD DiskSecPerRead BIGINT
END

GO

IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ServerDiskDW' AND COLUMN_NAME = 'DiskSecPerWrite')
BEGIN
	ALTER TABLE eddsdbo.ServerDiskDW
	ADD DiskSecPerWrite BIGINT
END

GO

IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ServerDiskDW' AND COLUMN_NAME = 'FrequencyPerfTime')
BEGIN
	ALTER TABLE eddsdbo.ServerDiskDW
	ADD FrequencyPerfTime BIGINT
END

GO

IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ServerDiskDW' AND COLUMN_NAME = 'DiskSecPerReadBase')
BEGIN
	ALTER TABLE eddsdbo.ServerDiskDW
	ADD DiskSecPerReadBase BIGINT
END

GO

IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ServerDiskDW' AND COLUMN_NAME = 'DiskSecPerWriteBase')
BEGIN
	ALTER TABLE eddsdbo.ServerDiskDW
	ADD DiskSecPerWriteBase BIGINT
END