USE EDDSPerformance
GO
ALTER DATABASE EDDSPerformance
MODIFY FILE
	( NAME = EDDSPerformance, FILEGROWTH = 1024MB )
GO
ALTER DATABASE EDDSPerformance
MODIFY FILE
	( NAME = EDDSPerformance_LOG, FILEGROWTH = 512MB )
