use [EddsPerformance]

IF NOT EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'EventSourceSystemControl' AND TABLE_SCHEMA = N'EDDSDBO') 
BEGIN
	CREATE TABLE [eddsdbo].[EventSourceSystemControl](
		[ID] [int] IDENTITY(1,1) NOT NULL,
		[State] [int] NOT NULL,
	 CONSTRAINT [PK_EventSourceSystemControl] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	
	INSERT INTO [eddsdbo].[EventSourceSystemControl]
           ([State])
     VALUES
           (1)
END