USE EDDSPerformance
GO

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'eddsdbo' AND TABLE_NAME = 'SQLServerSummary') 
AND NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SQLServerSummary' AND COLUMN_NAME = 'LowMemorySignalStateRatio')
BEGIN
	ALTER TABLE eddsdbo.SQLServerSummary
	ADD LowMemorySignalStateRatio DECIMAL(4,3) NULL
END