USE EDDSPerformance
GO

IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'QoS_VarscatOutputDetailCumulative' AND COLUMN_NAME = 'QueryID')
BEGIN
	ALTER TABLE eddsdbo.QoS_VarscatOutputDetailCumulative
	ADD QueryID UNIQUEIDENTIFIER NULL
END