USE EDDSPerformance
GO

--Go ahead and rename the table if it's there to normalize casing
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'eddsdbo' AND TABLE_NAME = 'TrustSendLog') 
BEGIN
	EXEC sp_rename 'eddsdbo.TRUSTSENDLOG', 'TrustSendLog';
END

GO

--Make sure the existing table gets the output column that was added later on
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'eddsdbo' AND TABLE_NAME = 'TrustSendLog') 
AND NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TrustSendLog' AND COLUMN_NAME = 'Output')
BEGIN
	ALTER TABLE eddsdbo.TrustSendLog
	ADD [OUTPUT] VARCHAR(MAX) NULL
END

GO

--If the column was already added, but has the old type (text), normalize that as well
IF EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TrustSendLog' AND COLUMN_NAME = 'Output')
BEGIN
	ALTER TABLE eddsdbo.TrustSendLog
	ALTER COLUMN [OUTPUT] VARCHAR(MAX)
END

GO

--Rename columns
IF EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TrustSendLog' AND COLUMN_NAME = 'LOG_ID')
BEGIN
	EXEC sp_rename 'eddsdbo.TrustSendLog.LOG_ID', 'LogId', 'COLUMN'
END

GO

IF EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TrustSendLog' AND COLUMN_NAME = 'DATE')
BEGIN
	EXEC sp_rename 'eddsdbo.TrustSendLog.DATE', 'ScoreDate', 'COLUMN'
END

GO

IF EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TrustSendLog' AND COLUMN_NAME = 'DATA')
BEGIN
	EXEC sp_rename 'eddsdbo.TrustSendLog.DATA', 'QualityData', 'COLUMN'
END

GO

IF EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TrustSendLog' AND COLUMN_NAME = 'SEC_DATA')
BEGIN
	EXEC sp_rename 'eddsdbo.TrustSendLog.SEC_DATA', 'DataHash', 'COLUMN'
END

GO

IF EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TrustSendLog' AND COLUMN_NAME = 'SUCCESS')
BEGIN
	EXEC sp_rename 'eddsdbo.TrustSendLog.SUCCESS', 'Success', 'COLUMN'
END

GO

IF EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TrustSendLog' AND COLUMN_NAME = 'OUTPUT')
BEGIN
	EXEC sp_rename 'eddsdbo.TrustSendLog.OUTPUT', 'Output', 'COLUMN'
END

GO

--Now make sure the existing table gets the new TransmissionDate column
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'eddsdbo' AND TABLE_NAME = 'TrustSendLog') 
AND NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TrustSendLog' AND COLUMN_NAME = 'TransmissionDate')
BEGIN
	ALTER TABLE eddsdbo.TrustSendLog
	ADD TransmissionDate DATETIME NOT NULL
	CONSTRAINT DF_TransmissionDate DEFAULT GETUTCDATE()
END