USE EDDSPerformance

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'eddsdbo' AND TABLE_NAME = 'QoS_UserXInstanceSummary')
BEGIN
	IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'QoS_UserXInstanceSummary' AND COLUMN_NAME = 'DocumentSearchScore')
	BEGIN
		ALTER TABLE eddsdbo.QoS_UserXInstanceSummary
		ADD DocumentSearchScore DECIMAL(10,3) NULL
	END
END