USE EDDSPerformance

IF EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SystemVersionHistory' AND COLUMN_NAME = 'ServerName')
BEGIN
	ALTER TABLE eddsdbo.SystemVersionHistory
	DROP COLUMN ServerName;
END
