USE EDDSPerformance;
GO

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'kIE_ActiveCases') DROP TABLE EDDSDBO.kIE_ActiveCases
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'kIE_DatesToAudit') DROP TABLE EDDSDBO.kIE_DatesToAudit
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'kIE_RankedDays') DROP TABLE EDDSDBO.kIE_RankedDays
IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'kIE_RunningQueriesXML') DROP TABLE EDDSDBO.kIE_RunningQueriesXML