USE EDDSPerformance
GO

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'eddsdbo' AND TABLE_NAME = 'SQLServerDW') 
AND NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SQLServerDW' AND COLUMN_NAME = 'LowMemorySignalState')
BEGIN
	ALTER TABLE eddsdbo.SQLServerDW
	ADD LowMemorySignalState BIT NULL
END