USE EDDSPerformance
GO

IF NOT EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'WebServerDW' AND TABLE_SCHEMA = N'EDDSDBO') 
BEGIN
	CREATE TABLE eddsdbo.WebServerDW
	(
		WebServerDWID INT IDENTITY(1,1),
		CreatedOn DATETIME,
		ServerID INT,
		HttpStatusCode INT,
		ResponseMessage NVARCHAR(MAX),
		IsAccessible BIT,
		CONSTRAINT [PK_WebServerDWID] PRIMARY KEY CLUSTERED 
		(
			WebServerDWID ASC
		)
	)
END
GO