USE [EDDSPerformance]
GO

/****** Object:  Table [eddsdbo].[SQLServerDW]    Script Date: 03/14/2014 11:06:49 ******/
IF NOT EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'SQLServerDW' AND TABLE_SCHEMA = N'EDDSDBO')
BEGIN
	CREATE TABLE [eddsdbo].[SQLServerDW](
		[SQLServerDWID] [int] IDENTITY(1,1) NOT NULL,
		[CreatedOn] [datetime] NOT NULL,
		[ServerID] [int] NOT NULL,
		[SQLPageLifeExpectancy] [decimal](10, 2) NULL,
	 CONSTRAINT [PK_SQLServerDW] PRIMARY KEY CLUSTERED 
	(
		[SQLServerDWID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO
