USE EDDSPerformance
GO

IF NOT EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'VirtualLogFileSummary' AND TABLE_SCHEMA = N'EDDSDBO') 
BEGIN
	CREATE TABLE eddsdbo.VirtualLogFileSummary
	(
		VLFSID INT IDENTITY(1,1),
		CONSTRAINT PK_VirtualLogFileSummary PRIMARY KEY CLUSTERED (VLFSID ASC),
		QoSHourID BIGINT,
		SummaryDayHour DATETIME,
		ServerArtifactID INT,
		DatabaseName NVARCHAR(150),
		VirtualLogFiles INT
	)
END
GO