USE [EDDSPerformance]
GO

IF NOT EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'SQLServerPageouts' AND TABLE_SCHEMA = N'EDDSDBO') 
BEGIN
	CREATE TABLE eddsdbo.SQLServerPageouts
	(
		SSPID INT IDENTITY (1,1),
		PRIMARY KEY (SSPID),
		ServerID INT,
		SummaryDayHour DATETIME,
		QoSHourID BIGINT,
		Pageouts INT
	)
END
GO